### ISSUE TITLE
Issue with "EVERY_NODE"

### ISSUE THREAD

**Issue by j3k0** [tutumcloud/haproxy#63]
Hi there,

Don't know if this issue is specific to tutum/haproxy

**Context**

I have a service deployed on tutum with below configuration.

Service `app` is deployed with strategy `EVERY_NODE` + `tag=compute`
Proxy is deployed with strategy `EVERY_NODE` + `tag=public`

Node A tags: `compute, public`
Node B tags: `compute`

**Issue**

`haproxy` is only linked with `app` running on `node A`. `node B` is not being used.

**Expected**

Proxy to load balance between `node A` and `node B`.

**Comment by fermayo** [comment]
Hello!

By design, links between every node services are done per node. In your case, to work around this, you could deploy your app service with "high availability" strategy matching the number of containers to the number of nodes and should work fine.

As this is a Tutum-specific issue, let's continue the conversation on the support ticket you raised with us.

Thanks!
